meta:
  title: Commbank Developer Portal
  description: 
  siteUrl: https://developer-portal-starter.redoc.ly
  keywords: Commbank developer portal, api portal cba, api reference docs
  lang: en-US
linkChecker:
  severity: warning
  options:
    CheckExternal: false
logo:
  image: ./images/commbank.svg
  altText: Redocly Training
toc:
  enable: true
oasDefinitions:
  openapilocal: ./openapi/sampleAPI/sampleapi.yaml
  petstore: https://api.redocly.com/registry/bundle/api-portal/Petstore/v1/openapi.yaml?branch=main
  sampleapi: https://api.redocly.com/registry/bundle/api-portal/Sample%20API/1.0/openapi.yaml?branch=main
  openapi3.1.0: https://api.redocly.com/registry/bundle/api-portal/Openapi%203.1.0%20sample/v1.0/openapi.yaml?branch=main
  openapidirectdebit: https://api.redocly.com/registry/bundle/api-portal/Direct%20DebitGITHUB/V0.1/openapi.yaml?branch=main
  # add links to definitions in our API registry by using a fully qualified URL.
stylesheets:
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap
  - https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,600,700&display=swap
#analytics:
  # ga:
  # note that GA doesn't work in the development environment
  #  trackingId: UA-45997213-1
#scripts:
#  - ./static/intercom.js
nav:

  - label: API Registry
    page: developer-portal/index.md

  - search: true

footer:
  copyrightText: © 2022 Commonwealth Bank of Australia ABN 48 123 123 124 AFSL and Australian credit licence 234945
  columns:
    - group: Legal
      items:
        - label: Terms of Use
          href: 'https://redoc.ly/subscription-agreement/'
        - label: Privacy Notice
          href: 'https://redoc.ly/privacy-notice/'
        - label: Cookie Notice
          href: 'https://redoc.ly/cookie-notice/'
    - group: Support
      items:
        - label: FAQ
          page: faq.md
        - label: Contact us
          page: contact.mdx
