openapi: 3.1.0
x-stoplight:
  id: fagyf8badhttq
info:
  title: Webhooks API
  version: '1.0'
  summary: Webhooks API
  description: Webhooks API
servers:
  - url: 'http://localhost:3000/v1/webhooks'
paths: {}
components:
  schemas:
    Webhoook:
      title: Webhoook
      x-stoplight:
        id: 80p35of09mhoh
      type: object
      properties:
        id:
          type: string
      description: TODO