# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/directDebit/payments.yml:
  info-license:
    - '#/info'
  operation-4xx-response:
    - '#/paths/~1payments/get/responses'
    - '#/paths/~1payments/post/responses'
    - '#/paths/~1payments~1{id}/get/responses'
    - '#/paths/~1payments~1{id}~1refund/post/responses'
    - '#/paths/~1payment-schedules/get/responses'
    - '#/paths/~1payment-schedules/post/responses'
    - '#/paths/~1payment-schedules~1{id}/get/responses'
  no-invalid-media-type-examples:
    - '#/paths/~1payments/post/requestBody/content/application~1json/schema'
  operation-2xx-response:
    - '#/paths/~1payments~1{id}/get/responses'
    - '#/paths/~1payment-schedules/get/responses'
    - '#/paths/~1payment-schedules~1{id}/get/responses'
  security-defined:
    - '#/paths/~1payments/get'
    - '#/paths/~1payments/post'
    - '#/paths/~1payments~1{id}/get'
    - '#/paths/~1payments~1{id}~1refund/post'
    - '#/paths/~1payment-schedules/get'
    - '#/paths/~1payment-schedules/post'
    - '#/paths/~1payment-schedules~1{id}/get'
  spec:
    - '#/components/schemas/payment/examples'
  # This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi/directDebit/directdebit.yaml:
  info-license:
    - '#/info'
  operation-4xx-response:
    - '#/paths/~1agreements/get/responses'
    - '#/paths/~1agreements/post/responses'
    - '#/paths/~1agreements~1{id}/get/responses'
    - '#/paths/~1agreements~1{id}/delete/responses'
    - '#/paths/~1agreements~1{id}/patch/responses'
    - '#/paths/~1agreements~1{id}~1status/patch/responses'
    - '#/paths/~1agreements~1{id}~1payments/post/responses'
  security-defined:
    - '#/paths/~1agreements/get'
    - '#/paths/~1agreements/post'
    - '#/paths/~1agreements~1{id}/get'
    - '#/paths/~1agreements~1{id}/delete'
    - '#/paths/~1agreements~1{id}/patch'
    - '#/paths/~1agreements~1{id}~1status/patch'
    - '#/paths/~1agreements~1{id}~1payments/post'


